pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Slab wallet
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.slabwallet.ca/
#
# 2. URL of this page
url:              http://slabwallet.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           SLAB - Don't flash your Cash

  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://goo.gl/dS27Py
  #
  # URL of a cover photo of your project
  cover_image:    http://media-cache-ak0.pinimg.com/originals/95/cb/81/95cb814f23d9f0596c0b4a2cdaceb094.jpg
  
  # Use a one-liner to describe your project
  description:    Slab - Great magic travel wallet that keeps your cash, memory, sim and credit cards safe.
#
# 4. Your Twitter handle
twitter_handle:   slabwallet
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  This is the SLAB wallet team greeting from Montreal. <br />
  First of all, thank you for signing up to our mailing list. <br />
  Here's to tell you that our project is now live on Kickstarter,
  and now we have to count on your support to not only back the project, but also share the love. ♥
